version: "3.9"

name: qualimind-dev

networks:
  qm-net:

services:
  # ---------- Server (Express + TS) ----------
  server:
    container_name: qm-server-dev
    build:
      context: ./server
      target: dev
      args:
        MODE: dev               
    command: ["pnpm", "prepare:dev"]   
    environment:
      NODE_ENV: development
      APP_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app          
      - /app/node_modules     
    networks: [qm-net]
    profiles: ["backend", "frontend", "r"]

#  ---------- Frontend (React + Vite) ----------
  frontend:
    container_name: qm-frontend-dev
    build:
      context: ./frontend
      target: dev
      args:
        MODE: dev
    environment:
      NODE_ENV: development
      APP_ENV: development
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - server
    networks: [qm-net]
    profiles: ["backend", "frontend", "r"]

  # ---------- R Engine (plumber) ----------
  # r-engine:
  #   container_name: qm-r
  #   build:
  #     context: ./apps/r-engine
  #     dockerfile: Dockerfile
  #   environment:
  #     R_ENVIRON_USER: /home/ruser/.Renviron
  #   ports:
  #     - "8000:8000"
  #   networks: [qm-net]
  #   profiles: ["r"]
